language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install: 
- pip install pep8 setuptools
- python setup.py install
script:
# Stye Check 
- python ./tests/pep8-git-pr-checker
# Automated Testing
- python -m unittest discover tests -v
